DROP TABLE activations;
DROP TABLE persistences;
DROP TABLE reminders;
DROP TABLE roles;
DROP TABLE role_users;
DROP TABLE throttle;
DROP TABLE users;
DROP TABLE password_resets;
TRUNCATE TABLE migrations;